# Generated by Django 3.0.5 on 2020-04-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip',
            field=models.IntegerField(max_length=6),
        ),
    ]
