# Generated by Django 3.0.5 on 2020-04-08 19:09

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_hub', '0002_auto_20200408_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=phone_field.models.PhoneField(max_length=20),
        ),
    ]
